# General
name: "EVLUG"
description: "Evansville Linux User Group"
url: http://www.evlug.com

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
twitter: EvansvilleLug
github: EV-LUG
google: +yourusername

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
