# General
name: "EVLUG"
description: "Evansville Linux User Group"
url: http://www.evlug.com

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]

paginate: 5
permalink: /:title

# Social share and comments.
twitter: EvansvilleLug
github: EV-LUG
facebook: evlug

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"